version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependency-cache-{{ checksum "mix.lock" }}
            - v3-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile --warnings-as-errors
      - run: mix compile
      - run:
          command: mix compile --warnings-as-errors
          environment:
            MIX_ENV: test
      - restore_cache:
          keys:
            - v3-plt-cache-{{ checksum "mix.lock" }}
            - v3-plt-cache
      - run: mix dialyzer --plt
      - run: mix dialyzer --halt-exit-status
      - run:
          command: mix coveralls.circle
          environment:
            MIX_ENV: test
      - run:
          command: mix do deps.get, deps.compile inchci.add
          environment:
            MIX_ENV: docs
      - save_cache:
          key: v3-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - save_cache:
          key: v3-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
